###
### Copyright (c) 2023 Carbon Community 
### All rights reserved
###
name: Client Build
concurrency: build-carbon-client

on:
  workflow_dispatch:

jobs:
  bootstrap:
    name: 🥾 Bootstrap
    runs-on: ubuntu-latest

    outputs:
      date:    ${{ steps.step1.outputs.date }}
      clock:   ${{ steps.step1.outputs.clock }}
      tag:     ${{ steps.step1.outputs.tag }}
      ref:     ${{ steps.step1.outputs.ref }}
      version: ${{ steps.step1.outputs.version }}

    steps:
      #- name: Log environment
      #  uses: crazy-max/ghaction-dump-context@v1
        
      - name: 🔗 Checkout source code from github
        uses: actions/checkout@v3

      - name: 📅 Prepare the environment
        id: step1
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "clock=$(date +'%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "tag=$(date +'%Yd%j')" >> $GITHUB_OUTPUT
          echo "ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=$(date +'1.%Y.%q%j.%M%S')" >> $GITHUB_OUTPUT

  # BUILD WINDOWS --------------------------------------------------------------
  build-windows:
    name: 💻 Windows
    needs: bootstrap
    runs-on: windows-latest
    continue-on-error: false
    
    steps:
    - name: 🔗 Checkout source code from github
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_ALL_REPO }}
        submodules: recursive
        
    - name: 🛤️ Setup the dotnet build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: 🔨 Built Carbon Client on Windows
      shell: cmd
      run: |
        set VERSION=${{ needs.bootstrap.outputs.version }}
        cd %GITHUB_WORKSPACE%\Tools\Build\win
        call %GITHUB_WORKSPACE%\Tools\Build\win\build_client_debug.bat Debug
        call %GITHUB_WORKSPACE%\Tools\Build\win\build_client_debug.bat Release

    - name: ⬆️ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-develop-windows
        path: |
          Release/Carbon.Client.Debug.info
          Release/Carbon.Client.Debug.zip
          Release/Carbon.Client.Release.info
          Release/Carbon.Client.Release.zip

  # RELEASE --------------------------------------------------------------------
  release-on-commit:
    name: 💾 Client Release
    needs: [ "bootstrap", "build-windows" ]
    runs-on: ubuntu-latest

    steps:
    - name: 🗑️ Delete existing release tag
      uses: dev-drprasad/delete-tag-and-release@92d94d77429cb0436597047a92369526a5824f50
      with:
        delete_release: true
        tag_name: client_build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 💤 Sleep for 5 seconds
      run: sleep 5s
      shell: bash

    - name: ⬇️ Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: Release

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: Release

    - name: 🏷️ Update release tag
      uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
      with:
        draft: false
        prerelease: true
        tag_name: client_build
        name: 'Client Build — v${{ needs.bootstrap.outputs.version }}'
        body: |
          Carbon 4 client (or "C4C") is a sub-project which allows extended communication between Carbon servers and clients running C4C. 
          It allows developers to load up various features and content server and client-side.
          
          Read [more] info about how to get started.

          ### How to install
          1. Download the `Carbon.Client.Release.zip` archive from the attachments below.
          2. Unzip the archive to the root of your Rust Client.
          3. Launch RustClient.exe (and not through Steam or Rust.exe, as EAC must be disabled).
          
          ### How to uninstall
          1. Move or remove the `winhttp.dll` from the root of your Rust client.
          2. Launch Rust through Steam or with EAC as usual. C4C is completely disabled.
          
          ${{ needs.build-linux.outputs.build_info }}

          [more]: https://docs.carbonmod.gg/docs/carbon-client/getting-started
        files: |
          Release/build-develop-windows/Carbon.Client.Release.info
          Release/build-develop-windows/Carbon.Client.Release.zip
